# Generated by Django 3.2.8 on 2023-04-05 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictureUrl', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=20)),
                ('candidates', models.CharField(max_length=100)),
                ('addtime', models.DateTimeField(default=datetime.datetime(2023, 4, 5, 14, 32, 1, 39565))),
            ],
            options={
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=88)),
                ('nickname', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=255)),
                ('sesion', models.IntegerField(default=0, max_length=11)),
                ('addtime', models.DateTimeField(default=datetime.datetime(2023, 4, 5, 14, 32, 1, 38568))),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
