# Generated by Django 3.2.8 on 2023-04-05 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, max_length=11)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2023, 4, 5, 13, 56, 56, 246434))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2023, 4, 5, 13, 56, 56, 246434))),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
    ]
